# SAM configuration file for multiple environments
version = 0.1

[default.global.parameters]
stack_name = "kitchen-tracker"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"

# Development Environment
[dev.deploy.parameters]
stack_name = "kitchen-tracker-dev"
s3_prefix = "kitchen-tracker-dev"
region = "us-east-1"
confirm_changeset = true
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Environment=dev"
]

# Production Environment  
[prod.deploy.parameters]
stack_name = "kitchen-tracker-prod"
s3_prefix = "kitchen-tracker-prod"
region = "us-east-1"
confirm_changeset = true
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Environment=prod"
]